name: pris

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter test and analyse
    runs-on: ubuntu-latest
    steps:
      - run: flutter pub get
      - run: flutter analyze
